name: libdoip CI

on:
    push:
    pull_request:

jobs:
    sonar:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
              with:
                # Disabling shallow clone is recommended for improving relevancy of reporting
                fetch-depth: 0
            - name: Sonar Static Code Analysis
              run: ./runsonarscanner.sh ${{ secrets.SONAR_TOKEN }} $GITHUB_REF

    build:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: ./makeindocker.sh
            - name: Test
              run: ./runtestindocker.sh
        
    build_raspberrypi:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: ./makeindocker.rpi.sh
            - name: Test
              run: ./runtestindocker.rpi.sh
                